const {JSDOM}=require(process.env.JSDOM_PATH||'jsdom');
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');
const root=path.join(__dirname,'..');
function client(lang){const filename=lang==='fr'?'index.html':`index.${lang}.html`;const dom=new JSDOM(fs.readFileSync(path.join(root,'dist',filename),'utf8'),{url:'https://example.test/dist/'+filename,runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window,ctx=dom.getInternalVMContext(),run=s=>vm.runInContext(s,ctx);w.HTMLMediaElement.prototype.play=function(){return Promise.resolve()};w.HTMLMediaElement.prototype.pause=function(){};w.scrollTo=()=>{};w.matchMedia=()=>({matches:true});w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'))};w.confirm=()=>true;w.prompt=()=>null;w.AbortController=AbortController;w.fetch=async()=>{throw Error('offline')};w.setInterval=()=>1;w.localStorage.setItem('aracne-welcome-v5','seen');for(const f of [`app.${lang}.js`,'catalog-v2.js','v2.js','v21.js','shared-trips.js','experience.js','collaboration-v3.js','v5.js','invitations-v51.js','beta.js'])run(fs.readFileSync(path.join(root,'dist',f),'utf8'));return {w,run,click:s=>{const el=w.document.querySelector(s);assert.ok(el,s);el.click()},close:()=>w.close()}}
module.exports={client};
if(require.main===module)(async()=>{for(const lang of ['fr','it','en','es']){const c=client(lang),{w,run}=c;
assert.equal(w.document.querySelector('#welcome').open,false,'intro remembers completion');
w.prompt=()=> 'Voyage A';w.aracneV5.create();run("state.notes.push({id:'private-a',text:'private latest',privacy:'private',day:-1});save()");const a=w.localStorage.getItem('aracne-v5-active');
w.prompt=()=> 'Voyage B';w.aracneV5.create();assert.equal(run('state.name'),'Voyage B');assert.equal(run('state.notes.length'),0);w.aracneV5.openTrips();c.click(`[data-v5-trip="${a}"]`);assert.equal(run('state.name'),'Voyage A');assert.equal(run('state.notes[0].text'),'private latest');
run("state.plan=[[{uid:'step-a',name:'Visit',desc:'',time:'10:00'}]];save()");await w.aracneV5.clearPlan();assert.equal(run('state.plan.length'),0);assert.equal(run('state.name'),'Voyage A');assert.equal(run('state.notes[0].text'),'private latest');
w.aracneV5.openHub();w.prompt=()=>null;c.click('#v5Backup');await Promise.resolve();assert.equal(w.aracneV5.store().trips[a].versions.length,1,'cancel creates no snapshot');
const base={name:'X',plan:[[{uid:'x',name:'A'}]],notes:[],expenses:[],journal:[]},l=structuredClone(base),r=structuredClone(base);l.plan[0][0].name='L';r.plan[0][0].name='R';assert.throws(()=>w.aracneShared._mergeDocs(base,l,r),/merge_conflict/);l.plan=[];assert.throws(()=>w.aracneShared._mergeDocs(base,l,r),/merge_conflict/);
const l2=structuredClone(base),r2=structuredClone(base);l2.plan[0].push({uid:'l',name:'L'});r2.plan[0].push({uid:'r',name:'R'});assert.equal(w.aracneShared._mergeDocs(base,l2,r2).plan[0].length,3);

run("state.plan=[[{uid:'pub',name:'Published',desc:'original',time:'10:00',status:'proposed'}]];save();show('plan')");c.click('[data-validate-step]');c.click('#finalizePlan');assert.equal(run('state.publishedBook.plan[0][0].name'),'Published');run("state.plan[0][0].name='Changed draft';save()");assert.equal(run('state.publishedBook.plan[0][0].name'),'Published');assert.equal(run('state.plan[0][0].status'),'modified');
await w.aracneV5.remove();assert.equal(w.aracneV5.store().trips[a],undefined);assert.equal(run('state.name'),'');assert.equal(w.localStorage.getItem('aracne-shared-v1'),null);
console.log(lang+': PASS solo multi-trip, private notes, clear/delete, cancelled snapshot, independent merge and conflicts');c.close()}})().catch(e=>{console.error(e);process.exitCode=1});
