'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(36).slice(2);
const money=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(n/100);
const kinds={city:'Villes & villages',beach:'Plage',boat:'Bateau',party:'Soirées',food:'À table',nature:'Nature',spa:'Spa & détente'};
const themes=[['evjf','✧','EVJF'],['evg','♧','EVG'],['friends','☺','Entre amis'],['couple','♡','En couple'],['family','⌂','En famille']];
const zones=[
{id:'gargano',name:'Gargano & Daunia',lat:41.882,lon:16.177,tags:['nature','beach','boat'],base:'Vieste',arrival:'Foggia',desc:'Falaises, villages et nature. Une base à Vieste pour le littoral ; une autre dans la Daunia pour l’intérieur.'},
{id:'imperiale',name:'Puglia Imperiale',lat:41.277,lon:16.417,tags:['city','food'],base:'Trani',arrival:'Bari',desc:'Ports, patrimoine et tables locales autour de Trani, Barletta et Andria.'},
{id:'bari',name:'Bari & la côte',lat:40.995,lon:17.220,tags:['city','beach','boat','party','food'],base:'Monopoli',arrival:'Bari',desc:'Bari, Polignano et Monopoli : une base côtière pour mêler découvertes, mer et sorties.'},
{id:'itria',name:'Vallée d’Itria',lat:40.755,lon:17.327,tags:['city','food','spa','nature'],base:'Martina Franca',arrival:'Brindisi',desc:'Villages blancs, trulli et campagne. Alternez balades et moments dans une masseria.'},
{id:'murgia',name:'Murgia, gravines & Taranto',lat:40.605,lon:16.806,tags:['nature','city','food'],base:'Laterza',arrival:'Bari',desc:'Paysages de gravines, bourgs de la Murgia et patrimoine de Taranto. Prévoyez les trajets.'},
{id:'salento',name:'Salento',lat:40.353,lon:18.172,tags:['beach','party','city','boat','food','spa'],base:'Lecce',arrival:'Brindisi',desc:'Lecce et les deux côtes. Choisissez vos plages selon les conditions du jour et vos déplacements.'}
];
const raw=[
['Vieste','gargano',41.882,16.177,'beach,city,boat','Vieille ville, littoral et idée de sortie en mer.'],['Peschici','gargano',41.948,16.013,'city,beach','Village perché et littoral du Gargano.'],['Foresta Umbra','gargano',41.819,15.995,'nature','Balade forestière : choisissez un sentier adapté au groupe.'],['Monte Sant’Angelo','gargano',41.706,15.960,'city','Patrimoine et ruelles du Gargano.'],['Bovino','gargano',41.249,15.343,'city,food','Une étape dans les villages des Monti Dauni.'],['Lucera','gargano',41.508,15.335,'city,food','Patrimoine de la Daunia et pause gourmande.'],['Îles Tremiti','gargano',42.121,15.505,'boat,nature,beach','Excursion à organiser séparément : bateau et météo à vérifier.'],
['Trani','imperiale',41.277,16.417,'city,food','Port, cathédrale et promenade en bord de mer.'],['Barletta','imperiale',41.320,16.285,'city,food','Centre historique et patrimoine.'],['Castel del Monte','imperiale',41.084,16.271,'city,nature','Visite du château : vérifier les billets et les horaires.'],['Bisceglie','imperiale',41.241,16.504,'city,beach,food','Port et promenade côtière.'],
['Bari Vecchia','bari',41.130,16.870,'city,food,party','Ruelles du vieux Bari, gastronomie et aperitivo.'],['Polignano a Mare','bari',40.995,17.220,'city,boat,beach','Belvédères et criques ; bateau selon disponibilité et état de mer.'],['Monopoli','bari',40.953,17.301,'city,beach,party,food','Vieux port, criques et dîner dans le centre.'],['Capitolo','bari',40.908,17.351,'beach,party','Littoral et sorties : vérifier les ouvertures saisonnières.'],['Giovinazzo','bari',41.187,16.673,'city,food','Petit port et centre historique.'],
['Alberobello','itria',40.783,17.237,'city','Une balade dans les quartiers de trulli.'],['Locorotondo','itria',40.754,17.327,'city,food','Ruelles blanches, panorama et dégustation à réserver.'],['Martina Franca','itria',40.705,17.338,'city,food','Centre baroque et spécialités de la vallée.'],['Cisternino','itria',40.743,17.427,'city,food','Village et dîner autour des spécialités locales.'],['Ostuni','itria',40.731,17.578,'city,food,spa','Ville blanche ; chercher une masseria ou un spa aux alentours.'],['Torre Canne','itria',40.840,17.468,'beach,spa','Bord de mer ; soins et établissements à vérifier avant de réserver.'],
['Altamura','murgia',40.827,16.550,'city,food','Centre ancien et découverte du pain local.'],['Gravina in Puglia','murgia',40.817,16.421,'city,nature','Patrimoine et paysage de gravine.'],['Laterza','murgia',40.629,16.798,'nature,city','Gravine et centre historique.'],['Taranto','murgia',40.474,17.243,'city,food,boat','Vieille ville et patrimoine maritime.'],['Castellaneta','murgia',40.628,16.936,'nature,city','Bourg et paysages de gravines.'],
['Lecce','salento',40.353,18.172,'city,food,party','Baroque, artisanat et dîner en ville.'],['Gallipoli','salento',40.055,17.990,'city,beach,party','Vieille ville et littoral ; soirées à vérifier selon la saison.'],['Baia Verde','salento',40.036,18.017,'beach,party','Plage et établissements saisonniers.'],['Otranto','salento',40.145,18.491,'city,beach,boat','Centre historique et littoral adriatique.'],['Porto Cesareo','salento',40.262,17.897,'beach,boat','Plages et sorties en mer à réserver.'],['Nardò','salento',40.180,18.032,'city,food','Centre baroque et pause gourmande.'],['Santa Maria di Leuca','salento',39.797,18.359,'boat,beach','À la pointe du Salento ; vérifier les conditions de mer.'],['Brindisi','salento',40.638,17.946,'city,food','Port et promenade avant ou après le voyage.'],['Santa Cesarea Terme','salento',40.037,18.456,'spa,beach','Littoral et détente : prestations thermales à vérifier.'],['Torre Guaceto','salento',40.714,17.797,'nature,beach','Réserve naturelle : respecter les accès et règles de protection.']
];
const places=raw.map((r,i)=>({id:'p'+i,name:r[0],zone:r[1],lat:r[2],lon:r[3],tags:r[4].split(','),desc:r[5]}));
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Europe/Rome'});
const defaults=()=>({version:1,theme:'evjf',name:'Notre EVJF dans les Pouilles',people:6,start:'',days:3,arrival:'Bari',budget:400,pace:'slow',transport:'driving',interests:['beach','food','party'],zone:null,plan:[],members:Array.from({length:6},(_,i)=>'Personne '+(i+1)),expenses:[],notes:[],splitLink:''});
let state=defaults(),view='prepare',day=0,map,layer,photoFile=null,weatherByZone={},weatherSequence=0;
function validate(s){const safeId=x=>typeof x==='string'&&/^[a-zA-Z0-9-]{1,100}$/.test(x);if(!s||s.version!==1||!themes.some(t=>t[0]===s.theme)||typeof s.name!=='string'||s.name.length>80||!Number.isInteger(s.people)||s.people<2||s.people>40||!Number.isInteger(s.days)||s.days<1||s.days>14||!Array.isArray(s.plan)||s.plan.length>14||!Array.isArray(s.members)||s.members.length!==s.people||s.members.some(x=>typeof x!=='string'||!x.trim()||x.length>60)||new Set(s.members).size!==s.people)throw Error('Copie non reconnue');if(typeof s.start!=='string'||(s.start&&!/^\d{4}-\d{2}-\d{2}$/.test(s.start))||!['Bari','Brindisi','Foggia','Libre'].includes(s.arrival)||!['slow','active'].includes(s.pace)||!['driving','transit'].includes(s.transport)||!Number.isFinite(s.budget)||s.budget<0||s.budget>100000||!Array.isArray(s.interests)||s.interests.some(x=>!kinds[x])||!Array.isArray(s.expenses)||!Array.isArray(s.notes)||s.notes.length>1000||s.expenses.length>2000)throw Error('Données invalides');for(const d of s.plan){if(!Array.isArray(d)||d.length>50)throw Error('Programme invalide');for(const p of d){if(!safeId(p.uid)||typeof p.name!=='string'||p.name.length>200||typeof p.desc!=='string'||p.desc.length>4000||typeof p.time!=='string'||(p.lat!=null&&(!Number.isFinite(p.lat)||Math.abs(p.lat)>90))||(p.lon!=null&&(!Number.isFinite(p.lon)||Math.abs(p.lon)>180)))throw Error('Étape invalide')}}for(const e of s.expenses){if(!safeId(e.id)||typeof e.title!=='string'||!Number.isInteger(e.cents)||e.cents<1||e.cents>10000000||!s.members.includes(e.payer)||!Array.isArray(e.who)||!e.who.length||e.who.some(n=>!s.members.includes(n))||new Set(e.who).size!==e.who.length)throw Error('Dépense invalide')}for(const n of s.notes){if(!safeId(n.id)||typeof n.text!=='string'||n.text.length>4000||!['private','group'].includes(n.privacy)||!Number.isInteger(n.day)||n.day< -1||n.day>=s.days)throw Error('Note invalide')}if(s.splitLink&&!validSplit(s.splitLink))throw Error('Lien de groupe invalide');return s}
try{const saved=localStorage.getItem('aracne-puglia-v1');if(saved)state=validate(JSON.parse(saved))}catch{setTimeout(()=>toast('La sauvegarde locale n’a pas pu être chargée. Vous pouvez importer une copie.'),400)}
function save(){try{localStorage.setItem('aracne-puglia-v1',JSON.stringify(state))}catch{toast('Sauvegarde locale indisponible. Exportez votre voyage.')}}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',4200)}
function show(v){view=v;$$('.view').forEach(e=>e.classList.toggle('active',e.id===v));$$('nav button').forEach(e=>e.classList.toggle('active',e.dataset.view===v));if(v==='map')setTimeout(drawMap,40);if(v==='plan')renderPlan();if(v==='budget')renderBudget();if(v==='notes')renderNotes();window.scrollTo({top:0,behavior:'smooth'})}
function dialog(title,html){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modal').showModal()}
$('#closeModal').onclick=()=>$('#modal').close();$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))$('#modal').close()});
$$('nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));$('.brand').onclick=e=>{e.preventDefault();show('prepare')};
function fillForm(){$('#tripName').value=state.name;$('#people').value=state.people;$('#start').value=state.start;$('#start').min=today();$('#days').innerHTML=Array.from({length:14},(_,i)=>`<option value="${i+1}">${i+1} jour${i?'s':''}</option>`).join('');$('#days').value=state.days;$('#arrival').value=state.arrival;$('#budgetTarget').value=state.budget;$('#pace').value=state.pace;$('#transport').value=state.transport;renderChoices()}
function renderChoices(){$('#themes').innerHTML=themes.map(t=>`<button type="button" class="theme ${state.theme===t[0]?'selected':''}" data-theme="${t[0]}" aria-pressed="${state.theme===t[0]}"><b aria-hidden="true">${t[1]}</b>${t[2]}</button>`).join('');$('#interests').innerHTML=Object.entries(kinds).map(([k,n])=>`<button type="button" class="chip ${state.interests.includes(k)?'selected':''}" data-interest="${k}" aria-pressed="${state.interests.includes(k)}">${n}</button>`).join('');$$('[data-theme]').forEach(b=>b.onclick=()=>{state.theme=b.dataset.theme;save();renderChoices()});$$('[data-interest]').forEach(b=>b.onclick=()=>{const k=b.dataset.interest;state.interests=state.interests.includes(k)?state.interests.filter(x=>x!==k):[...state.interests,k];save();renderChoices()})}
function syncForm(){const count=Number($('#people').value),duration=Number($('#days').value);if(state.expenses.length&&count!==state.people){toast('Le groupe a déjà des dépenses : gardez sa taille pour préserver les comptes.');$('#people').value=state.people;return false}if(state.plan.length>duration&&state.plan.slice(duration).some(x=>x.length)){if(!confirm('Réduire la durée supprimera les étapes des derniers jours. Continuer ?'))return false}Object.assign(state,{name:$('#tripName').value.trim(),people:count,start:$('#start').value,days:duration,arrival:$('#arrival').value,budget:Number($('#budgetTarget').value)||0,pace:$('#pace').value,transport:$('#transport').value});while(state.members.length<count)state.members.push('Personne '+(state.members.length+1));state.members=state.members.slice(0,count);state.plan=state.plan.slice(0,duration);state.notes.forEach(n=>{if(n.day>=duration)n.day=-1});day=Math.min(day,duration-1);save();return true}
$('#tripForm').onsubmit=async e=>{e.preventDefault();if(!syncForm())return;if(!state.interests.length){toast('Choisissez au moins une envie.');return}$('#recommendations').hidden=false;weatherByZone={};renderZones();$('#recommendations').scrollIntoView({behavior:'smooth',block:'start'});await weather()};
function score(z){let n=state.interests.filter(t=>z.tags.includes(t)).length*10;if(z.arrival===state.arrival)n+=state.days<4?10:4;if(['evjf','evg','friends'].includes(state.theme)&&['bari','salento'].includes(z.id)&&state.interests.includes('party'))n+=3;if(state.theme==='family'&&z.tags.includes('nature'))n+=3;const w=weatherByZone[z.id];if(w)n+=w.bonus;return n}
function renderZones(){const sorted=[...zones].sort((a,b)=>score(b)-score(a));$('#zoneCards').innerHTML=sorted.map((z,i)=>{const w=weatherByZone[z.id];return `<article class="zoneCard"><div><span class="eyebrow">${i===0?'NOTRE PREMIÈRE PISTE':esc(z.base)}</span><h3>${esc(z.name)}</h3><p>${esc(z.desc)}</p><span class="tag">${state.interests.filter(t=>z.tags.includes(t)).map(t=>kinds[t]).join(' · ')||'Une autre ambiance à explorer'}</span>${w?`<p class="weather">${w.temp} °C max. moy. · ${w.rain} % pluie max. · vent max. ${w.wind} km/h<br>${w.count}/${state.days} jours couverts · ${esc(z.base)} / point représentatif</p>`:''}</div><button class="primary" data-zone="${z.id}">Choisir cette zone</button></article>`}).join('');$$('[data-zone]').forEach(b=>b.onclick=()=>generate(b.dataset.zone))}
async function weather(){const seq=++weatherSequence;const diff=(new Date(state.start+'T00:00:00Z')-new Date(today()+'T00:00:00Z'))/86400000;const node=$('#weatherStatus');if(diff<0||diff>15){node.textContent='Dates hors fenêtre de prévision. Les zones sont classées selon vos envies et votre arrivée, sans avantage météo supposé. Pour la plage et les soirées, vérifiez la saison d’ouverture ; comparez la météo à l’approche du départ.';return}node.textContent='Comparaison de la météo dans les six zones…';try{const q=new URLSearchParams({latitude:zones.map(z=>z.lat).join(','),longitude:zones.map(z=>z.lon).join(','),daily:'temperature_2m_max,precipitation_probability_max,wind_speed_10m_max',timezone:'Europe/Rome',forecast_days:'16'});const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),12000);let res;try{res=await fetch('https://api.open-meteo.com/v1/forecast?'+q,{signal:controller.signal})}finally{clearTimeout(timeout)}if(!res.ok)throw Error();const data=await res.json();if(seq!==weatherSequence)return;if(!Array.isArray(data)||data.length!==zones.length)throw Error();const result={};data.forEach((d,i)=>{const indexes=d.daily.time.map((t,j)=>({t,j})).filter(v=>v.t>=state.start&&v.t<dateAt(state.days));const valid=indexes.filter(({j})=>Number.isFinite(d.daily.temperature_2m_max[j])&&Number.isFinite(d.daily.precipitation_probability_max[j])&&Number.isFinite(d.daily.wind_speed_10m_max[j]));if(!valid.length)return;let temp=Math.round(valid.reduce((a,v)=>a+d.daily.temperature_2m_max[v.j],0)/valid.length),rain=Math.max(...valid.map(v=>d.daily.precipitation_probability_max[v.j])),wind=Math.round(Math.max(...valid.map(v=>d.daily.wind_speed_10m_max[v.j])));result[zones[i].id]={temp,rain,wind,count:valid.length,bonus:(100-rain)/15-Math.max(0,wind-20)/5+(state.interests.includes('beach')?Math.max(-5,5-Math.abs(temp-26)):0)}});weatherByZone=result;node.textContent=`Prévisions Open-Meteo consultées à ${new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}. Pluie, vent et température complètent vos envies. ${diff+state.days>16?'Le séjour dépasse la fenêtre : comparaison partielle. ':''}Ce sont des points représentatifs, pas une garantie pour chaque plage ; conditions de mer à vérifier.`;renderZones()}catch{if(seq===weatherSequence){weatherByZone={};node.textContent='Météo indisponible pour le moment. Le classement utilise uniquement vos envies et votre arrivée ; aucune prévision n’est inventée.';renderZones()}}}
function dateAt(d){if(!state.start)return '';let dt=new Date(state.start+'T12:00:00Z');dt.setUTCDate(dt.getUTCDate()+d);return dt.toISOString().slice(0,10)}
function dayLabel(d){const t=dateAt(d);return 'Jour '+(d+1)+(t?' · '+new Date(t+'T12:00:00').toLocaleDateString('fr-FR',{day:'numeric',month:'short'}):'')}
function distance(a,b){const rad=x=>x*Math.PI/180;const x=rad(b.lat-a.lat),y=rad(b.lon-a.lon);return 6371*2*Math.asin(Math.sqrt(Math.sin(x/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(y/2)**2))}
function generate(zone){if(state.plan.some(d=>d.length)&&!confirm('Remplacer le programme actuel par une nouvelle proposition ? Vos notes et dépenses seront conservées.'))return;state.zone=zone;const z=zones.find(x=>x.id===zone);let pool=places.filter(p=>p.zone===zone&&p.name!=='Îles Tremiti').sort((a,b)=>b.tags.filter(t=>state.interests.includes(t)).length-a.tags.filter(t=>state.interests.includes(t)).length);const limit=state.pace==='slow'?2:3;state.plan=[];for(let d=0;d<state.days;d++){if(!pool.length){state.plan.push([{uid:uid(),name:'Journée libre à '+z.base,desc:'Gardez du temps pour vos envies, ou ajoutez une activité sur la carte.',time:'10:00',lat:null,lon:null}]);continue}let first=pool.shift(),chosen=[first];pool.sort((a,b)=>distance(first,a)-distance(first,b));while(chosen.length<limit&&pool.length&&distance(first,pool[0])<(state.transport==='transit'?25:65))chosen.push(pool.shift());state.plan.push(chosen.map((p,i)=>({...p,uid:uid(),time:['10:00','15:00','18:00'][i],desc:p.desc+(p.tags.includes('party')&&state.interests.includes('party')?' Pour une sortie le soir, cherchez un établissement ouvert à vos dates et prévoyez le retour.':'')})))}day=0;save();show('plan');toast('Votre première proposition est prête. Tout reste modifiable.')}
function allSteps(){return state.plan.flat()}
function renderPlan(){$('#planTitle').textContent=state.name;$('#planSummary').innerHTML=`<p>${state.people} personnes · ${state.days} jours · ${themes.find(t=>t[0]===state.theme)[2]}${state.zone?' · '+esc(zones.find(z=>z.id===state.zone)?.name||''):''}</p><p class="notice">${state.transport==='transit'?'Les horaires de bus et trains ne sont pas vérifiés. Vérifiez chaque liaison avant de réserver.':'Temps libres et heures proposés : ajustez-les selon vos réservations et les temps de route.'} ${state.budget?'Budget cible : '+money(state.budget*100)+' / personne, sans estimation de prix des activités.':''}</p>`;$('#dayTabs').innerHTML=Array.from({length:state.days},(_,i)=>`<button class="${day===i?'active':''}" data-day="${i}">${esc(dayLabel(i))}</button>`).join('');$$('[data-day]').forEach(b=>b.onclick=()=>{day=Number(b.dataset.day);renderPlan()});const arr=state.plan[day]||[];$('#itinerary').innerHTML=arr.length?arr.map((p,i)=>`<article class="step"><span class="number">${i+1}</span><div class="stepContent"><span class="eyebrow">${esc(p.time)||'HORAIRE LIBRE'}</span><h3>${esc(p.name)}</h3><p>${esc(p.desc)}</p><div class="actions"><button class="mini" data-edit="${esc(p.uid)}">Modifier</button><button class="mini" data-up="${i}" ${i===0?'disabled':''} aria-label="Monter ${esc(p.name)}">↑</button><button class="mini" data-down="${i}" ${i===arr.length-1?'disabled':''} aria-label="Descendre ${esc(p.name)}">↓</button><button class="mini" data-remove="${i}" aria-label="Retirer ${esc(p.name)}">Retirer</button>${Number.isFinite(p.lat)?`<a class="mini" href="${waze(p)}" target="_blank" rel="noopener">Waze</a>`:''}</div></div></article>`).join(''):'<div class="empty">Cette journée est à vous.<br>Ajoutez vos lieux depuis la carte ou une étape libre.</div>';$$('[data-edit]').forEach(b=>b.onclick=()=>editStep(b.dataset.edit));$$('[data-up]').forEach(b=>b.onclick=()=>move(Number(b.dataset.up),-1));$$('[data-down]').forEach(b=>b.onclick=()=>move(Number(b.dataset.down),1));$$('[data-remove]').forEach(b=>b.onclick=()=>{arr.splice(Number(b.dataset.remove),1);save();renderPlan()});const route=arr.filter(p=>Number.isFinite(p.lat));if(state.transport==='transit'&&route.length>1){$('#routeActions').innerHTML=route.slice(1).map((p,i)=>`<a class="secondary" href="${mapsUrl([route[i],p])}" target="_blank" rel="noopener">Liaison ${i+1} · Google Maps</a>`).join('');return}$('#routeActions').innerHTML=route.length?`<a class="primary" href="${mapsUrl(route)}" target="_blank" rel="noopener">Parcours du jour · Google Maps</a>${route.length>5?'<p class="small">Les cinq premières étapes sont incluses. Pour la suite, ouvrez chaque étape séparément.</p>':''}`:''}
function move(i,delta){const arr=state.plan[day];[arr[i],arr[i+delta]]=[arr[i+delta],arr[i]];save();renderPlan()}
function mapsUrl(arr){arr=arr.slice(0,5);const q=new URLSearchParams({api:'1',destination:arr.at(-1).lat+','+arr.at(-1).lon,travelmode:state.transport});if(arr.length>1)q.set('origin',arr[0].lat+','+arr[0].lon);if(arr.length>2&&state.transport!=='transit')q.set('waypoints',arr.slice(1,-1).map(p=>p.lat+','+p.lon).join('|'));return 'https://www.google.com/maps/dir/?'+q}
function waze(p){return 'https://www.waze.com/ul?'+new URLSearchParams({ll:p.lat+','+p.lon,navigate:'yes'})}
function editStep(id){const old=(state.plan[day]||[]).find(p=>p.uid===id);dialog(old?'Modifier l’étape':'Une étape à vous',`<form id="stepForm"><label>Nom<input id="stepName" maxlength="200" required value="${esc(old?.name||'')}"></label><div class="grid2"><label>Horaire<input id="stepTime" type="time" value="${esc(old?.time||'10:00')}"></label><label>Jour<select id="stepDay">${Array.from({length:state.days},(_,i)=>`<option value="${i}" ${i===day?'selected':''}>${esc(dayLabel(i))}</option>`).join('')}</select></label></div><label>Votre idée / adresse<textarea id="stepDesc" rows="3" maxlength="4000">${esc(old?.desc||'')}</textarea></label><div class="grid2"><label>Latitude (facultatif)<input id="stepLat" type="number" step="any" min="-90" max="90" value="${old?.lat??''}"></label><label>Longitude (facultatif)<input id="stepLon" type="number" step="any" min="-180" max="180" value="${old?.lon??''}"></label></div><p class="small">Sans coordonnées, votre étape apparaît dans le programme mais pas sur la carte.</p><button class="primary">Enregistrer l’étape</button></form>`);$('#stepForm').onsubmit=e=>{e.preventDefault();if(Boolean($('#stepLat').value)!==Boolean($('#stepLon').value)){toast('Renseignez les deux coordonnées, ou laissez les deux vides.');return}const target=Number($('#stepDay').value);const p={...(old||{}),uid:old?.uid||uid(),name:$('#stepName').value.trim(),desc:$('#stepDesc').value,time:$('#stepTime').value,lat:$('#stepLat').value===''?null:Number($('#stepLat').value),lon:$('#stepLon').value===''?null:Number($('#stepLon').value)};if(old)state.plan[day]=state.plan[day].filter(x=>x.uid!==id);while(state.plan.length<state.days)state.plan.push([]);state.plan[target].push(p);day=target;save();$('#modal').close();renderPlan()}}
$('#addManual').onclick=()=>editStep();$('#explore').onclick=()=>show('map');
$('#zoneFilter').innerHTML+=zones.map(z=>`<option value="${z.id}">${esc(z.name)}</option>`).join('');$('#zoneFilter').onchange=drawMap;$('#search').oninput=drawMap;
function filtered(){const norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const q=norm($('#search').value.trim());return places.filter(p=>($('#zoneFilter').value==='all'||p.zone===$('#zoneFilter').value)&&norm([p.name,p.desc,...p.tags.map(t=>kinds[t])].join(' ')).includes(q))}
function drawMap(){const list=filtered();$('#placeCount').textContent=list.length+' lieux';$('#places').innerHTML=list.map(p=>`<article class="place"><span class="tag">${p.tags.slice(0,2).map(t=>kinds[t]).join(' · ')}</span><h3>${esc(p.name)}</h3><p>${esc(p.desc)}</p><button class="secondary" data-add="${p.id}">＋ Au programme</button></article>`).join('')||'<p>Aucun lieu pour cette recherche.</p>';$$('[data-add]').forEach(b=>b.onclick=()=>choosePlace(b.dataset.add));if(!window.L){$('#mapFallback').textContent='Carte indisponible. Tous les lieux restent accessibles dans la liste.';return}if(!map){$('#mapCanvas').innerHTML='';map=L.map('mapCanvas').setView([41,17],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map);layer=L.layerGroup().addTo(map)}layer.clearLayers();list.forEach(p=>{const included=allSteps().some(s=>s.id===p.id);const marker=L.marker([p.lat,p.lon],{icon:L.divIcon({className:'',html:`<div class="pin ${included?'inplan':''}">${included?'✓':'•'}</div>`,iconSize:[27,27]})}).addTo(layer);const box=document.createElement('div');box.innerHTML=`<strong>${esc(p.name)}</strong><br>${esc(p.desc)}<br>`;const b=document.createElement('button');b.textContent='Ajouter au programme';b.className='secondary';b.onclick=()=>choosePlace(p.id);box.append(b);marker.bindPopup(box)});const coords=(state.plan[day]||[]).filter(p=>Number.isFinite(p.lat)).map(p=>[p.lat,p.lon]);if(coords.length>1)L.polyline(coords,{color:'#e94057',weight:3,dashArray:'6 8'}).addTo(layer);map.invalidateSize();if(list.length)map.fitBounds(L.latLngBounds(list.map(p=>[p.lat,p.lon])),{padding:[25,25],maxZoom:11})}
function choosePlace(id){const p=places.find(p=>p.id===id);dialog(p.name,`<p>${esc(p.desc)}</p><label>Ajouter à quel jour ?<select id="addDay">${Array.from({length:state.days},(_,i)=>`<option value="${i}" ${i===day?'selected':''}>${esc(dayLabel(i))}</option>`).join('')}</select></label><button class="primary" id="confirmAdd">Ajouter cette étape</button>`);$('#confirmAdd').onclick=()=>{day=Number($('#addDay').value);while(state.plan.length<state.days)state.plan.push([]);state.plan[day].push({...p,uid:uid(),time:''});save();$('#modal').close();drawMap();toast(p.name+' ajouté au jour '+(day+1))}}
function renderBudget(){const total=state.expenses.reduce((a,e)=>a+e.cents,0);$('#budgetSummary').innerHTML=`<div class="stat"><strong>${money(total)}</strong><span>Dépenses saisies</span></div><div class="stat"><strong>${money(Math.round(total/state.people))}</strong><span>Moyenne / personne</span></div><div class="stat"><strong>${state.people}</strong><span>Dans le groupe</span></div>`;$('#members').value=state.members.join(', ');$('#payer').innerHTML=state.members.map(n=>`<option>${esc(n)}</option>`).join('');$('#beneficiaries').innerHTML=state.members.map((n,i)=>`<label class="check"><input type="checkbox" value="${i}" checked>${esc(n)}</label>`).join('');$('#expenseList').innerHTML=state.expenses.map(e=>`<article class="expense"><div><strong>${esc(e.title)}</strong><p>${esc(e.payer)} a payé · partagé entre ${e.who.length} personnes</p><button class="textBtn" data-delete-exp="${e.id}">Supprimer</button></div><strong>${money(e.cents)}</strong></article>`).join('');$$('[data-delete-exp]').forEach(b=>b.onclick=()=>{if(confirm('Supprimer cette dépense ?')){state.expenses=state.expenses.filter(e=>e.id!==b.dataset.deleteExp);save();renderBudget()}});const transfers=settle();$('#settlements').innerHTML=transfers.length?transfers.map(t=>`<div class="settle"><b>${esc(t.from)}</b> rembourse <b>${money(t.cents)}</b> à ${esc(t.to)}</div>`).join(''):'<p>Aucun remboursement à prévoir.</p>';$('#splitLink').value=state.splitLink;$('#openSplit').hidden=!state.splitLink;if(state.splitLink)$('#openSplit').href=state.splitLink}
function settle(){const balance=Object.fromEntries(state.members.map(n=>[n,0]));for(const e of state.expenses){balance[e.payer]+=e.cents;const each=Math.floor(e.cents/e.who.length),rest=e.cents%e.who.length;e.who.forEach((n,i)=>balance[n]-=each+(i<rest?1:0))}const debt=Object.entries(balance).filter(([,v])=>v<0).map(([n,v])=>({n,v:-v})),credit=Object.entries(balance).filter(([,v])=>v>0).map(([n,v])=>({n,v}));const out=[];let i=0,j=0;while(i<debt.length&&j<credit.length){const c=Math.min(debt[i].v,credit[j].v);out.push({from:debt[i].n,to:credit[j].n,cents:c});debt[i].v-=c;credit[j].v-=c;if(!debt[i].v)i++;if(!credit[j].v)j++}return out}
$('#saveMembers').onclick=()=>{const list=$('#members').value.split(',').map(x=>x.trim()).filter(Boolean);if(list.length!==state.people||new Set(list).size!==list.length||list.some(x=>x.length>60)){toast('Saisissez exactement '+state.people+' prénoms distincts (60 caractères maximum).');return}if(state.expenses.length&&state.members.some((n,i)=>list[i]!==n)){toast('Les noms sont liés aux dépenses existantes. Supprimez ou exportez les dépenses avant de renommer le groupe.');return}state.members=list;save();renderBudget();toast('Participants enregistrés')};
$('#expenseForm').onsubmit=e=>{e.preventDefault();const who=$$('#beneficiaries input:checked').map(x=>state.members[Number(x.value)]);if(!who.length){toast('Choisissez au moins un bénéficiaire.');return}state.expenses.push({id:uid(),title:$('#expenseTitle').value.trim(),cents:Math.round(Number($('#amount').value)*100),payer:$('#payer').value,who});save();$('#expenseForm').reset();renderBudget();toast('Dépense ajoutée')};
function validSplit(link){try{const u=new URL(link);return u.protocol==='https:'&&['splitwise.com','tricount.com','tricount.page.link','tricount.app'].some(d=>u.hostname===d||u.hostname.endsWith('.'+d))}catch{return false}}
$('#saveSplit').onclick=()=>{let l=$('#splitLink').value.trim();if(l&&!validSplit(l)){toast('Utilisez un lien HTTPS officiel Splitwise ou Tricount.');return}state.splitLink=l;save();renderBudget();toast('Lien enregistré')};
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),15000)}
$('#exportExpenses').onclick=()=>{const cell=v=>'"'+String(v).replace(/^[=+@-]/,"'"+'$&').replace(/"/g,'""')+'"';const rows=[['Dépense','Montant EUR','Payé par','Bénéficiaires'],...state.expenses.map(e=>[e.title,(e.cents/100).toFixed(2),e.payer,e.who.join(' | ')])];download(new Blob(['\uFEFF'+rows.map(r=>r.map(cell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}),'aracne-depenses.csv')};
function renderNotes(){$('#noteDay').innerHTML='<option value="-1">Tout le voyage</option>'+Array.from({length:state.days},(_,i)=>`<option value="${i}">${esc(dayLabel(i))}</option>`).join('');$('#noteList').innerHTML=state.notes.map(n=>`<article class="noteCard"><div class="small">${n.privacy==='private'?'Personnelle':'Pour le groupe'} · ${n.day<0?'Tout le voyage':esc(dayLabel(n.day))}</div><div>${esc(n.text)}</div><div class="actions"><button class="textBtn" data-edit-note="${n.id}">Modifier</button><button class="textBtn" data-delete-note="${n.id}">Supprimer</button></div></article>`).join('');$$('[data-delete-note]').forEach(b=>b.onclick=()=>{if(confirm('Supprimer cette note ?')){state.notes=state.notes.filter(n=>n.id!==b.dataset.deleteNote);save();renderNotes()}});$$('[data-edit-note]').forEach(b=>b.onclick=()=>{const n=state.notes.find(n=>n.id===b.dataset.editNote);dialog('Modifier la note',`<form id="editNoteForm"><label>Note<textarea id="editNote" rows="5" required maxlength="4000">${esc(n.text)}</textarea></label><label>Visibilité<select id="editPrivacy"><option value="private" ${n.privacy==='private'?'selected':''}>Personnelle</option><option value="group" ${n.privacy==='group'?'selected':''}>Pour le groupe</option></select></label><button class="primary">Enregistrer</button></form>`);$('#editNoteForm').onsubmit=e=>{e.preventDefault();n.text=$('#editNote').value;n.privacy=$('#editPrivacy').value;save();$('#modal').close();renderNotes()}})}
$('#noteForm').onsubmit=e=>{e.preventDefault();state.notes.unshift({id:uid(),text:$('#noteText').value,day:Number($('#noteDay').value),privacy:$('#notePrivacy').value});save();$('#noteText').value='';renderNotes();toast('Note gardée dans votre carnet')};
function shareText(scope,includeNotes){const indexes=scope==='all'?Array.from({length:state.days},(_,i)=>i):[Number(scope)];let lines=[state.name,state.people+' personnes · '+themes.find(t=>t[0]===state.theme)[2],''];for(const d of indexes){lines.push(dayLabel(d));const arr=state.plan[d]||[];arr.forEach(p=>lines.push((p.time?p.time+' · ':'')+p.name+(p.desc?' — '+p.desc:'')));if(!arr.length)lines.push('Programme libre');const route=arr.filter(p=>Number.isFinite(p.lat));if(state.transport==='transit'&&route.length>1)route.slice(1).forEach((p,i)=>lines.push('Liaison '+(i+1)+' : '+mapsUrl([route[i],p])));else if(route.length)lines.push('Itinéraire'+(route.length>5?' (5 premières étapes)':'')+' : '+mapsUrl(route));lines.push('')}if(includeNotes){const notes=state.notes.filter(n=>n.privacy==='group'&&(n.day===-1||indexes.includes(n.day)));if(notes.length)lines.push('Notes du groupe',...notes.map(n=>'• '+n.text))}lines.push('Préparé avec Il Volo d’Aracne · Puglia');return lines.join('\n')}
function shareDialog(){dialog('Partager le voyage',`<p>Envoyez le programme complet ou une seule journée. Les notes personnelles et les dépenses restent exclues.</p><label>Que partager ?<select id="shareScope"><option value="all">Tout le programme</option>${Array.from({length:state.days},(_,i)=>`<option value="${i}">${esc(dayLabel(i))}</option>`).join('')}</select></label><label class="check"><input id="includeNotes" type="checkbox">Inclure les notes marquées « Pour le groupe »</label><label>Aperçu<textarea id="sharePreview" rows="7" readonly></textarea></label><div class="actions"><a id="wa" class="primary" target="_blank" rel="noopener">WhatsApp</a><button id="nativeShare" class="secondary">Partager…</button><button id="copyShare" class="textBtn">Copier le texte</button></div><p class="small">Ce partage transmet une copie du programme, pas un espace collaboratif synchronisé.</p>`);const update=()=>{const t=shareText($('#shareScope').value,$('#includeNotes').checked);$('#sharePreview').value=t;$('#wa').href='https://wa.me/?text='+encodeURIComponent(t)};$('#shareScope').onchange=update;$('#includeNotes').onchange=update;update();$('#nativeShare').onclick=async()=>{try{if(navigator.share)await navigator.share({title:state.name,text:$('#sharePreview').value});else await copy($('#sharePreview').value)}catch(e){if(e.name!=='AbortError')toast('Partage indisponible : copiez le texte ou utilisez WhatsApp.')}};$('#copyShare').onclick=()=>copy($('#sharePreview').value)}
async function copy(t){try{await navigator.clipboard.writeText(t);toast('Texte copié')}catch{toast('Sélectionnez le texte dans l’aperçu pour le copier.')}}
$('#shareTop').onclick=shareDialog;$('#sharePlan').onclick=shareDialog;
$('#export').onclick=()=>download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),'aracne-voyage.json');
$('#import').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>2e6)throw Error();const candidate=validate(JSON.parse(await f.text()));if(!confirm('Remplacer votre brouillon local par cette copie ? Exportez d’abord le brouillon si vous souhaitez le conserver.'))return;state=candidate;day=0;weatherSequence++;weatherByZone={};$('#recommendations').hidden=true;save();fillForm();show('prepare');toast('Voyage importé')}catch{toast('Cette copie est invalide ou trop volumineuse. Votre voyage est conservé.')}finally{e.target.value=''}};
$('#storyPhoto').onchange=e=>{const f=e.target.files[0];if(f&&f.size>15e6){toast('Choisissez une photo de moins de 15 Mo.');return}photoFile=f;$('#photoStatus').textContent=f?'Photo choisie : '+f.name:''};
function wrapText(ctx,text,x,y,maxWidth,lineHeight,maxLines=5){let words=text.split(/\s+/),line='',lines=[];for(const word of words){const test=line?line+' '+word:word;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=word}else line=test}if(line)lines.push(line);lines.slice(0,maxLines).forEach((l,i)=>ctx.fillText(l+(i===maxLines-1&&lines.length>maxLines?'…':''),x,y+i*lineHeight));return y+Math.min(lines.length,maxLines)*lineHeight}
$('#createStory').onclick=async()=>{try{const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1920;const c=canvas.getContext('2d');const grad=c.createLinearGradient(0,0,1080,1920);grad.addColorStop(0,'#692676');grad.addColorStop(.55,'#e94057');grad.addColorStop(1,'#f27121');c.fillStyle=grad;c.fillRect(0,0,1080,1920);if(photoFile){const img=await createImageBitmap(photoFile);const s=Math.max(1080/img.width,1920/img.height);c.drawImage(img,(1080-img.width*s)/2,(1920-img.height*s)/2,img.width*s,img.height*s);img.close();c.fillStyle='#24132ca8';c.fillRect(0,0,1080,1920)}c.fillStyle='white';c.font='600 30px sans-serif';c.fillText('IL VOLO D’ARACNE',85,150);c.font='28px sans-serif';c.fillText('PUGLIA · INSIEME',85,205);c.font='700 72px sans-serif';let y=wrapText(c,state.name,85,440,900,85,3);c.font='32px sans-serif';c.fillText(state.people+' personnes · '+dayLabel(day),85,y+35);y+=180;c.font='500 43px sans-serif';const arr=(state.plan[day]||[]).slice(0,3);if(!arr.length)c.fillText('Nos souvenirs commencent ici.',85,y);arr.forEach((p,i)=>{y=wrapText(c,(i+1)+'. '+p.name,85,y,880,60,2)+32});if((state.plan[day]||[]).length>3){c.font='28px sans-serif';c.fillText('Et d’autres moments à découvrir…',85,y+20)}c.font='28px sans-serif';c.fillText('Nos Pouilles, à notre façon.',85,1735);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error();const url=URL.createObjectURL(blob);dialog('Votre story est prête',`<img src="${url}" alt="Aperçu de la story"><div class="actions"><button class="primary" id="downloadStory">Télécharger l’image</button><button class="secondary" id="shareStory">Partager l’image</button></div><p class="small">Importez ensuite l’image dans Instagram ou Facebook. Aucun contenu n’est publié automatiquement.</p>`);$('#downloadStory').onclick=()=>download(blob,'aracne-story.png');$('#shareStory').onclick=async()=>{const f=new File([blob],'aracne-story.png',{type:'image/png'});try{if(navigator.canShare?.({files:[f]}))await navigator.share({files:[f],title:state.name});else{download(blob,'aracne-story.png');toast('Image téléchargée : ouvrez votre réseau social pour l’importer.')}}catch(e){if(e.name!=='AbortError')toast('Téléchargez l’image pour la partager.')}};$('#modal').addEventListener('close',()=>URL.revokeObjectURL(url),{once:true})}catch{toast('Photo non lisible. Essayez une image JPEG/PNG, ou créez la story sans photo.')}};
fillForm();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_aracne_trip',title:'Lire le voyage Aracne',description:'Retourne le programme et les paramètres du voyage ouvert, sans notes personnelles ni dépenses.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({name:state.name,people:state.people,start:state.start,days:state.days,plan:state.plan})})).catch(()=>{})}catch{}}
